<?php

declare(strict_types=1);

namespace Cycle\SmartMapper;

use Cycle\ORM\Command\CommandInterface;
use Cycle\ORM\ORMInterface;
use Cycle\ORM\SchemaInterface;
use Cycle\ORM\Transaction\CommandGenerator;
use Cycle\ORM\Transaction\Tuple;
use Cycle\SmartMapper\Dispatcher\Dispatcher;
use Cycle\SmartMapper\Dispatcher\ListenerProvider;
use Cycle\SmartMapper\Event\Mapper\Command\OnCreate;
use Psr\EventDispatcher\EventDispatcherInterface;

final class EventCommandGenerator extends CommandGenerator
{
    private EventDispatcherInterface $eventDispatcher;

    public function __construct(SchemaInterface $schema)
    {
        $listenerProvider = new ListenerProvider($schema);
        $this->eventDispatcher = new Dispatcher($listenerProvider);
    }

    protected function storeEntity(Tuple $tuple, bool $isNew): ?CommandInterface
    {
        $event = new OnCreate($tuple->node->getRole(), $tuple->mapper, $tuple->entity, $tuple->node, $tuple->state);
        $event->command = parent::storeEntity($tuple, $isNew); // TODO: Change the autogenerated stub

        $event = $this->eventDispatcher->dispatch($event);

        return $event->command;
    }

    protected function generateParentStoreCommand(
        ORMInterface $orm,
        Tuple $tuple,
        string $parentRole,
        bool $isNew
    ): ?CommandInterface {
        $parentMapper = $orm->getMapper($parentRole);

        $event = new OnCreate($parentRole, $parentMapper, $tuple->entity, $tuple->node, $tuple->state);
        $event->command = $isNew
            ? $parentMapper->queueCreate($tuple->entity, $tuple->node, $tuple->state)
            : $parentMapper->queueUpdate($tuple->entity, $tuple->node, $tuple->state);

        $event = $this->eventDispatcher->dispatch($event);

        return $event->command;
    }
}
